import { Injectable } from '@angular/core';
import { Observable, of, delay } from 'rxjs';
import { StatementMonth, StatementListResponse } from '../../../consignor/models/consignor.models';

@Injectable({
  providedIn: 'root'
})
export class MockStatementService {

  private mockMonthlyStatements: StatementMonth[] = [
    {
      year: 2024,
      month: 12,
      monthName: 'December 2024',
      salesCount: 12,
      totalEarnings: 485.00,
      payoutCount: 2
    },
    {
      year: 2024,
      month: 11,
      monthName: 'November 2024',
      salesCount: 8,
      totalEarnings: 312.50,
      payoutCount: 1
    },
    {
      year: 2024,
      month: 10,
      monthName: 'October 2024',
      salesCount: 15,
      totalEarnings: 198.75,
      payoutCount: 1
    },
    {
      year: 2024,
      month: 9,
      monthName: 'September 2024',
      salesCount: 6,
      totalEarnings: 267.00,
      payoutCount: 1
    },
    {
      year: 2024,
      month: 8,
      monthName: 'August 2024',
      salesCount: 9,
      totalEarnings: 143.25,
      payoutCount: 1
    }
  ];

  getMonthlyStatements(): Observable<StatementListResponse> {
    // Sort by year and month (newest first)
    const sortedStatements = [...this.mockMonthlyStatements].sort((a, b) => {
      if (a.year !== b.year) {
        return b.year - a.year;
      }
      return b.month - a.month;
    });

    return of({ statements: sortedStatements }).pipe(delay(500));
  }

  getEmptyStatements(): Observable<StatementListResponse> {
    return of({ statements: [] }).pipe(delay(300));
  }

  downloadMonthlyPdf(year: number, month: number): Observable<Blob> {
    // Mock PDF generation - simulate network delay
    const pdfContent = this.generateMonthlyPDF(year, month);
    const blob = new Blob([pdfContent], { type: 'application/pdf' });
    return of(blob).pipe(delay(1200));
  }

  private generateMonthlyPDF(year: number, month: number): string {
    const monthNames = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];

    const monthName = monthNames[month - 1];

    // This is a mock - in reality you'd use a PDF generation library or API call
    return `MONTHLY STATEMENT - ${monthName.toUpperCase()} ${year}

Main Street Consignment
123 Main Street, Anytown, USA 12345
(555) 123-4567

Statement For: Jane Smith (Consignor ID: JS-1234)
Period: ${monthName} 1-${this.getDaysInMonth(year, month)}, ${year}
Generated: ${new Date().toLocaleDateString()}

This is mock PDF content. In a real implementation, this would be
generated by the backend API and include:

- Complete sales details for the month
- Payout information and calculations
- Commission breakdowns
- Account balance information
- Professional formatting and branding

Month Summary:
- Sales Count: ${this.getStatementData(year, month)?.salesCount || 0}
- Total Earnings: ${this.getStatementData(year, month)?.totalEarnings.toFixed(2) || '0.00'}
- Payouts: ${this.getStatementData(year, month)?.payoutCount || 0}

[PDF content would continue with detailed transaction listings]`;
  }

  private getStatementData(year: number, month: number): StatementMonth | undefined {
    return this.mockMonthlyStatements.find(s => s.year === year && s.month === month);
  }

  private getDaysInMonth(year: number, month: number): number {
    return new Date(year, month, 0).getDate();
  }
}